#!/bin/sh
#==============================================================================
#                      _ _ _       _
#   _ __ ___  __ _  __| | (_)_ __ | | __
#  | '__/ _ \/ _` |/ _` | | | '_ \| |/ /
#  | | |  __/ (_| | (_| | | | | | |   <
#  |_|  \___|\__,_|\__,_|_|_|_| |_|_|\_\
#==============================================================================
# TOOL: READLINK
#==============================================================================

_posix_adapter__readlink__print_help() {
  >&2 echo '=============================================================================='
  >&2 echo ''
  >&2 echo '  posix_adapter__readlink --help'
  >&2 echo '  posix_adapter__readlink [--canonicalize] <path>'
  >&2 echo ''
  >&2 echo '------------------------------------------------------------------------------'
  >&2 echo ' Execution mapping function for the "readlink" command line tool with a'
  >&2 echo ' uniform interface.'
  >&2 echo '------------------------------------------------------------------------------'
  >&2 echo ' Globals:'
  >&2 echo '   None'
  >&2 echo ' Options:'
  >&2 echo '   --help - Prints out the help message and exits.'
  >&2 echo '   --canonicalize - readlink compatible flag for the original -f flag.'
  >&2 echo ' Arguments:'
  >&2 echo '   [1] path - Path that should be resolved.'
  >&2 echo ' STDIN:'
  >&2 echo '   Input passed to the mapped command.'
  >&2 echo '------------------------------------------------------------------------------'
  >&2 echo ' Output variables:'
  >&2 echo '   None'
  >&2 echo ' STDOUT:'
  >&2 echo '   Output of the mapped command.'
  >&2 echo ' STDERR:'
  >&2 echo '   Error output of the mapped command.'
  >&2 echo ' Status:'
  >&2 echo '   0  - Call was successful.'
  >&2 echo '   .. - Call failed with its error status.'
  >&2 echo '   98 - Invalid parameter configuration.'
  >&2 echo '   99 - No compatible call style was found.'
  >&2 echo '=============================================================================='
}

posix_adapter__readlink() {
  posix_adapter__flag__canonicalize='0'

  posix_adapter__flag__path='0'
  posix_adapter__value__path=''

  while [ "$#" -gt '0' ]
  do
    case "$1" in
      --canonicalize)
        posix_adapter__flag__canonicalize='1'
        shift
        ;;
      --[!-]*)
        _posix_adapter__readlink__report_invalid_parameter \
          "Unexpected option '${1}'!" \
          'You can only use the available options.'
        ;;
      -[!-]*)
        _posix_adapter__readlink__report_invalid_parameter \
          "Invalid single dashed option '${1}'!" \
          "posix_adapter only uses double dashed options like '--option'."
        ;;
      *)
        if [ "$posix_adapter__flag__path" -eq '0' ]
        then
          posix_adapter__flag__path='1'
          posix_adapter__value__path="$1"
          shift
        else
          _posix_adapter__readlink__report_invalid_parameter \
            'Unexpected parameter!' \
            "Parameter '${1}' is unexpected!"
        fi
        ;;
    esac
  done

  if [ "$posix_adapter__flag__path" -eq '0' ]
  then
    _posix_adapter__readlink__report_invalid_parameter \
      'Missing <path> argument!' \
      'To be able to use readlink, you need to specify a path to work with.'
  fi

  # Assembling the decision string.
  # ,-- canonicalize
  # 0
  posix_adapter__decision="${posix_adapter__flag__canonicalize}"

  case "$(uname -s)" in
    Linux)
      _posix_adapter__readlink__linux \
        "$posix_adapter__decision" \
        "$posix_adapter__value__path"
      ;;

    Darwin)
      _posix_adapter__readlink__darwin \
        "$posix_adapter__decision" \
        "$posix_adapter__value__path"
      ;;

    *)
      _posix_adapter__readlink__report_incompatible_call \
        "Unsupported platform '$(uname -s)'!" \
        'The tool is only implemented for Linux and Darwin so far.'
      ;;
  esac
}

#==============================================================================
# Linux based call mapping function.
#------------------------------------------------------------------------------
# Globals:
#   None
# Options:
#   None
# Arguments:
#   [1] decision_string - String that decodes the optional parameter presence.
#   [2] value_path - Path value.
# STDIN:
#   Input passed to the mapped command.
#------------------------------------------------------------------------------
# Output variables:
#   None
# STDOUT:
#   Mapped command's output.
# STDERR:
#   Mapped command's error output. Mapping error output.
# Status:
#   0  - Call succeeded.
#   .. - Call failed with it's error status
#==============================================================================
_posix_adapter__readlink__linux() {
  posix_adapter__decision_string="$1"
  posix_adapter__value__path="$2"

  case "$posix_adapter__decision_string" in
  # ,-- canonicalize
    0)
      readlink \
        \
        "$posix_adapter__value__path" \

      ;;
  # ,-- canonicalize
    1)
      readlink \
        -f \
        "$posix_adapter__value__path" \

      ;;
    *)
      _posix_adapter__readlink__report_incompatible_call \
        'Unexpected parameter combination!' \
        'You can only use the available options.'
      ;;
  esac
}

#==============================================================================
# Darwin based call mapping function.
#------------------------------------------------------------------------------
# Globals:
#   None
# Options:
#   None
# Arguments:
#   [1] decision_string - String that decodes the optional parameter presence.
#   [2] value_path - Path value.
# STDIN:
#   Input passed to the mapped command.
#------------------------------------------------------------------------------
# Output variables:
#   None
# STDOUT:
#   Mapped command's output.
# STDERR:
#   Mapped command's error output. Mapping error output.
# Status:
#   0  - Call succeeded.
#   .. - Call failed with it's error status
#==============================================================================
_posix_adapter__readlink__darwin() {
  posix_adapter__decision_string="$1"
  posix_adapter__value__path="$2"

  case "$posix_adapter__decision_string" in
  # ,-- canonicalize
    0)
      readlink \
        \
        "$posix_adapter__value__path" \

      ;;
  # ,-- canonicalize
    1)
      if ! readlink -f "$posix_adapter__value__path" 2>/dev/null
      then
        # Yep we are using python as a last resort..
        if command -v python >/dev/null
        then
          python -c \
            'import os,sys; print(os.path.realpath(os.path.expanduser(sys.argv[1])))' \
            "$posix_adapter__value__path"

        elif command -v python3 >/dev/null
        then
          python3 -c \
            'import os,sys; print(os.path.realpath(os.path.expanduser(sys.argv[1])))' \
            "$posix_adapter__value__path"

        else
          _posix_adapter__readlink__report_incompatible_call \
            'No python nor python3 executable was found.' \
            'Posix adapter is out of options to provide the desired functionality..'
        fi
      fi
      ;;
    *)
      _posix_adapter__readlink__report_incompatible_call \
        'Unexpected parameter combination!' \
        'You can only use the available options.'
      ;;
  esac
}

#==============================================================================
# Invalid parameter error reporting helper function.
#------------------------------------------------------------------------------
# Globals:
#   None
# Options:
#   None
# Arguments:
#   [1] reason - Reason of the error.
#   [2] details - More details about the error.
# STDIN:
#   None
#------------------------------------------------------------------------------
# Output variables:
#   None
# STDOUT:
#   None
# STDERR:
#   Reported error.
# Status:
#   98  - The function will terminate the execution.
#==============================================================================
_posix_adapter__readlink__report_invalid_parameter() {
  reason="$1"
  details="$2"
  >&2 echo "ERROR | posix_adapter__readlink | reason  | ${reason}"
  >&2 echo "ERROR | posix_adapter__readlink | details | ${details}"
  _posix_adapter__readlink__print_help
  exit 98
}

#==============================================================================
# Incompatible call error reporting helper function.
#------------------------------------------------------------------------------
# Globals:
#   None
# Options:
#   None
# Arguments:
#   [1] reason - Reason of the error.
#   [2] details - More details about the error.
# STDIN:
#   None
#------------------------------------------------------------------------------
# Output variables:
#   None
# STDOUT:
#   None
# STDERR:
#   Reported error.
# Status:
#   99  - The function will terminate the execution.
#==============================================================================
_posix_adapter__readlink__report_incompatible_call() {
  reason="$1"
  details="$2"
  >&2 echo "ERROR | posix_adapter__readlink | reason  | ${reason}"
  >&2 echo "ERROR | posix_adapter__readlink | details | ${details}"
  _posix_adapter__readlink__print_help
  exit 99
}

#==============================================================================
# ENTRY POINT
#==============================================================================

# If the script is called directly, call the internal function.
case $0 in
  *posix_adapter__readlink)
    posix_adapter__readlink "$@"
    ;;
esac
