#!/bin/sh
#==============================================================================
#                  _             _   _
#   _ __ ___  __ _| |_ __   __ _| |_| |__
#  | '__/ _ \/ _` | | '_ \ / _` | __| '_ \
#  | | |  __/ (_| | | |_) | (_| | |_| | | |
#  |_|  \___|\__,_|_| .__/ \__,_|\__|_| |_|
#===================|_|========================================================
# TOOL: REALPATH
#==============================================================================

_posix_adapter__realpath__print_help() {
  >&2 echo '=============================================================================='
  >&2 echo ''
  >&2 echo '  posix_adapter__realpath --help'
  >&2 echo '  posix_adapter__realpath [--no-symlinks] <target_path>'
  >&2 echo '  posix_adapter__realpath [--no-symlinks] --relative-to <path> <target_path>'
  >&2 echo ''
  >&2 echo '------------------------------------------------------------------------------'
  >&2 echo ' Execution mapping function for the "realpath" command line tool with a'
  >&2 echo ' uniform interface.'
  >&2 echo '------------------------------------------------------------------------------'
  >&2 echo ' Globals:'
  >&2 echo '   None'
  >&2 echo ' Options:'
  >&2 echo '   --help - Prints out the help message and exits.'
  >&2 echo '   --no-symlinks - realpath compatible flag for the -s flag.'
  >&2 echo ' Arguments:'
  >&2 echo '   [1] path - Path that should be resolved.'
  >&2 echo ' STDIN:'
  >&2 echo '   Input passed to the mapped command.'
  >&2 echo '------------------------------------------------------------------------------'
  >&2 echo ' Output variables:'
  >&2 echo '   None'
  >&2 echo ' STDOUT:'
  >&2 echo '   Output of the mapped command.'
  >&2 echo ' STDERR:'
  >&2 echo '   Error output of the mapped command.'
  >&2 echo ' Status:'
  >&2 echo '   0  - Call was successful.'
  >&2 echo '   .. - Call failed with its error status.'
  >&2 echo '   98 - Invalid parameter configuration.'
  >&2 echo '   99 - No compatible call style was found.'
  >&2 echo '=============================================================================='
}

posix_adapter__realpath() {
  posix_adapter__flag__no_symlinks='0'

  posix_adapter__flag__relative_to='0'
  posix_adapter__value__relative_to=''

  posix_adapter__flag__path='0'
  posix_adapter__value__path=''

  while [ "$#" -gt '0' ]
  do
    case "$1" in
      --no-symlinks)
        posix_adapter__flag__no_symlinks='1'
        shift
        ;;
      --relative-to)
        posix_adapter__flag__relative_to='1'
        posix_adapter__value__relative_to="$2"
        shift
        shift
        ;;
      --[!-]*)
        _posix_adapter__realpath__report_invalid_parameter \
          "Unexpected option '${1}'!" \
          'You can only use the available options.'
        ;;
      -[!-]*)
        _posix_adapter__realpath__report_invalid_parameter \
          "Invalid single dashed option '${1}'!" \
          "posix_adapter only uses double dashed options like '--option'."
        ;;
      *)
        if [ "$posix_adapter__flag__path" -eq '0' ]
        then
          posix_adapter__flag__path='1'
          posix_adapter__value__path="$1"
          shift
        else
          _posix_adapter__realpath__report_invalid_parameter \
            'Unexpected parameter!' \
            "Parameter '${1}' is unexpected!"
        fi
        ;;
    esac
  done

  if [ "$posix_adapter__flag__path" -eq '0' ]
  then
    _posix_adapter__realpath__report_invalid_parameter \
      'Missing <path> argument!' \
      'To be able to use realpath, you need to specify a path to work with.'
  fi

  # Assembling the decision string.
  # ,--- no_symlinks
  # |,-- relative-to
  # 00
  posix_adapter__decision="${posix_adapter__flag__no_symlinks}"
  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__relative_to}"

  case "$(uname -s)" in
    Linux)
      _posix_adapter__realpath__linux \
        "$posix_adapter__decision" \
        "$posix_adapter__value__relative_to" \
        "$posix_adapter__value__path"
      ;;

    Darwin)
      _posix_adapter__realpath__darwin \
        "$posix_adapter__decision" \
        "$posix_adapter__value__relative_to" \
        "$posix_adapter__value__path"
      ;;

    *)
      _posix_adapter__realpath__report_incompatible_call \
        "Unsupported platform '$(uname -s)'!" \
        'The tool is only implemented for Linux and Darwin so far.'
      ;;
  esac
}

#==============================================================================
# Linux based call mapping function.
#------------------------------------------------------------------------------
# Globals:
#   None
# Options:
#   None
# Arguments:
#   [1] decision_string - String that decodes the optional parameter presence.
#   [2] posix_adapter__value__relative_to - Path value.
#   [3] value_path - Path value.
# STDIN:
#   Input passed to the mapped command.
#------------------------------------------------------------------------------
# Output variables:
#   None
# STDOUT:
#   Mapped command's output.
# STDERR:
#   Mapped command's error output. Mapping error output.
# Status:
#   0  - Call succeeded.
#   .. - Call failed with it's error status
#==============================================================================
_posix_adapter__realpath__linux() {
  posix_adapter__decision_string="$1"
  posix_adapter__value__relative_to="$2"
  posix_adapter__value__path="$3"

  case "$posix_adapter__decision_string" in
  # ,--- no_symlinks
  # |,-- relative-to
    00)
      realpath \
        \
        \
        "$posix_adapter__value__path" \

      ;;
  # ,--- no_symlinks
  # |,-- relative-to
    01)
      realpath \
        \
        --relative-to="$posix_adapter__value__relative_to" \
        "$posix_adapter__value__path" \

      ;;
  # ,--- no_symlinks
  # |,-- relative-to
    10)
      realpath \
        -s \
        \
        "$posix_adapter__value__path" \

      ;;
  # ,--- no_symlinks
  # |,-- relative-to
    11)
      realpath \
        -s \
        --relative-to="$posix_adapter__value__relative_to" \
        "$posix_adapter__value__path" \

      ;;
    *)
      _posix_adapter__realpath__report_incompatible_call \
        'Unexpected parameter combination!' \
        'You can only use the available options.'
      ;;
  esac
}

#==============================================================================
# Darwin based call mapping function.
#------------------------------------------------------------------------------
# Globals:
#   None
# Options:
#   None
# Arguments:
#   [1] decision_string - String that decodes the optional parameter presence.
#   [2] posix_adapter__value__relative_to - Path value.
#   [3] value_path - Path value.
# STDIN:
#   Input passed to the mapped command.
#------------------------------------------------------------------------------
# Output variables:
#   None
# STDOUT:
#   Mapped command's output.
# STDERR:
#   Mapped command's error output. Mapping error output.
# Status:
#   0  - Call succeeded.
#   .. - Call failed with it's error status
#==============================================================================
_posix_adapter__realpath__darwin() {
  posix_adapter__decision_string="$1"
  posix_adapter__value__relative_to="$2"
  posix_adapter__value__path="$3"

  case "$posix_adapter__decision_string" in
  # ,--- no_symlinks
  # |,-- relative-to
    00)
      if ! realpath "$posix_adapter__value__path" 2>/dev/null
      then
        if command -v python >/dev/null
        then
          python -c \
            'from os.path import expanduser,realpath;import sys;print(realpath(expanduser(sys.argv[1])))' \
            "$posix_adapter__value__path"

        elif command -v python3 >/dev/null
        then
          python3 -c \
            'from os.path import expanduser,realpath;import sys;print(realpath(expanduser(sys.argv[1])))' \
            "$posix_adapter__value__path"

        else
          _posix_adapter__realpath__report_incompatible_call \
            'No python nor python3 executable was found.' \
            'Posix adapter is out of options to provide the desired functionality..'
        fi
      fi
      ;;
  # ,--- no_symlinks
  # |,-- relative-to
    01)
      if ! realpath --relative-to="$posix_adapter__value__relative_to" "$posix_adapter__value__path" 2>/dev/null
      then
        if command -v python >/dev/null
        then
          python -c \
            'from os.path import relpath,expanduser,realpath;import sys;print(relpath(realpath(expanduser(sys.argv[1])),realpath(expanduser(sys.argv[2]))))' \
            "$posix_adapter__value__path" "$posix_adapter__value__relative_to"

        elif command -v python3 >/dev/null
        then
          python3 -c \
            'from os.path import relpath,expanduser,realpath;import sys;print(relpath(realpath(expanduser(sys.argv[1])),realpath(expanduser(sys.argv[2]))))' \
            "$posix_adapter__value__path" "$posix_adapter__value__relative_to"

        else
          _posix_adapter__realpath__report_incompatible_call \
            'No python nor python3 executable was found.' \
            'Posix adapter is out of options to provide the desired functionality..'
        fi
      fi
      ;;
  # ,--- no_symlinks
  # |,-- relative-to
    10)
      if ! realpath -s "$posix_adapter__value__path" 2>/dev/null
      then
        if command -v python >/dev/null
        then
          python -c \
            'from os.path import expanduser,abspath;import sys;print(abspath(expanduser(sys.argv[1])))' \
            "$posix_adapter__value__path"

        elif command -v python3 >/dev/null
        then
          python3 -c \
            'from os.path import expanduser,abspath;import sys;print(abspath(expanduser(sys.argv[1])))' \
            "$posix_adapter__value__path"

        else
          _posix_adapter__realpath__report_incompatible_call \
            'No python nor python3 executable was found.' \
            'Posix adapter is out of options to provide the desired functionality..'
        fi
      fi
      ;;
  # ,--- no_symlinks
  # |,-- relative-to
    11)
      if ! realpath --relative-to="$posix_adapter__value__relative_to" "$posix_adapter__value__path" 2>/dev/null
      then
        if command -v python >/dev/null
        then
          python -c \
            'from os.path import relpath,expanduser,abspath;import sys;print(relpath(abspath(expanduser(sys.argv[1])),abspath(expanduser(sys.argv[2]))))' \
            "$posix_adapter__value__path" "$posix_adapter__value__relative_to"

        elif command -v python3 >/dev/null
        then
          python3 -c \
            'from os.path import relpath,expanduser,abspath;import sys;print(relpath(abspath(expanduser(sys.argv[1])),abspath(expanduser(sys.argv[2]))))' \
            "$posix_adapter__value__path" "$posix_adapter__value__relative_to"

        else
          _posix_adapter__realpath__report_incompatible_call \
            'No python nor python3 executable was found.' \
            'Posix adapter is out of options to provide the desired functionality..'
        fi
      fi
      ;;
    *)
      _posix_adapter__realpath__report_incompatible_call \
        'Unexpected parameter combination!' \
        'You can only use the available options.'
      ;;
  esac
}

#==============================================================================
# Invalid parameter error reporting helper function.
#------------------------------------------------------------------------------
# Globals:
#   None
# Options:
#   None
# Arguments:
#   [1] reason - Reason of the error.
#   [2] details - More details about the error.
# STDIN:
#   None
#------------------------------------------------------------------------------
# Output variables:
#   None
# STDOUT:
#   None
# STDERR:
#   Reported error.
# Status:
#   98  - The function will terminate the execution.
#==============================================================================
_posix_adapter__realpath__report_invalid_parameter() {
  reason="$1"
  details="$2"
  >&2 echo "ERROR | posix_adapter__realpath | reason  | ${reason}"
  >&2 echo "ERROR | posix_adapter__realpath | details | ${details}"
  _posix_adapter__realpath__print_help
  exit 98
}

#==============================================================================
# Incompatible call error reporting helper function.
#------------------------------------------------------------------------------
# Globals:
#   None
# Options:
#   None
# Arguments:
#   [1] reason - Reason of the error.
#   [2] details - More details about the error.
# STDIN:
#   None
#------------------------------------------------------------------------------
# Output variables:
#   None
# STDOUT:
#   None
# STDERR:
#   Reported error.
# Status:
#   99  - The function will terminate the execution.
#==============================================================================
_posix_adapter__realpath__report_incompatible_call() {
  reason="$1"
  details="$2"
  >&2 echo "ERROR | posix_adapter__realpath | reason  | ${reason}"
  >&2 echo "ERROR | posix_adapter__realpath | details | ${details}"
  _posix_adapter__realpath__print_help
  exit 99
}

#==============================================================================
# ENTRY POINT
#==============================================================================

# If the script is called directly, call the internal function.
case $0 in
  *posix_adapter__realpath)
    posix_adapter__realpath "$@"
    ;;
esac
