#!/bin/sh
#==============================================================================
#   _                   _
#  | |_ ___  _   _  ___| |__
#  | __/ _ \| | | |/ __| '_ \
#  | || (_) | |_| | (__| | | |
#   \__\___/ \__,_|\___|_| |_|
#==============================================================================
# TOOL: TOUCH
#==============================================================================

_posix_adapter__touch__print_help() {
  >&2 echo '=============================================================================='
  >&2 echo ''
  >&2 echo '  posix_adapter__touch --help'
  >&2 echo '  posix_adapter__touch <path>'
  >&2 echo ''
  >&2 echo '------------------------------------------------------------------------------'
  >&2 echo ' Execution mapping function for the "touch" command line tool with a uniform'
  >&2 echo ' interface.'
  >&2 echo '------------------------------------------------------------------------------'
  >&2 echo ' Globals:'
  >&2 echo '   None'
  >&2 echo ' Options:'
  >&2 echo '   --help - Prints out the help message and exits.'
  >&2 echo ' Arguments:'
  >&2 echo '   [1] path - Path that needs to be touched.'
  >&2 echo ' STDIN:'
  >&2 echo '   Input passed to the mapped command.'
  >&2 echo '------------------------------------------------------------------------------'
  >&2 echo ' Output variables:'
  >&2 echo '   None'
  >&2 echo ' STDOUT:'
  >&2 echo '   Output of the mapped command.'
  >&2 echo ' STDERR:'
  >&2 echo '   Error output of the mapped command.'
  >&2 echo ' Status:'
  >&2 echo '   0  - Call was successful.'
  >&2 echo '   .. - Call failed with its error status.'
  >&2 echo '   98 - Invalid parameter configuration.'
  >&2 echo '   99 - No compatible call style was found.'
  >&2 echo '=============================================================================='
}

posix_adapter__touch() {
  if [ "$#" -eq 0 ]
  then
    _posix_adapter__touch__report_invalid_parameter \
      'Missing <path> parameter' \
      'This function does not take options.'
  elif [ "$#" -eq 1 ]
  then
    case "$1" in
    --[!-]*)
        _posix_adapter__touch__report_invalid_parameter \
          "Unexpected option '${1}'!" \
          'This function does not take options.'
        ;;
    -[!-]*)
        _posix_adapter__touch__report_invalid_parameter \
          "Invalid single dashed option '${1}'!" \
          "posix_adapter only uses double dashed options like '--option'."
        ;;
    esac

    touch "$1"

  else
    _posix_adapter__touch__report_invalid_parameter \
      'Unexpected parameter count!' \
      "Only 1 parameter is expected, got ${#}!"
  fi
}

#==============================================================================
# Invalid parameter error reporting helper function.
#------------------------------------------------------------------------------
# Globals:
#   None
# Options:
#   None
# Arguments:
#   [1] reason - Reason of the error.
#   [2] details - More details about the error.
# STDIN:
#   None
#------------------------------------------------------------------------------
# Output variables:
#   None
# STDOUT:
#   None
# STDERR:
#   Reported error.
# Status:
#   98  - The function will terminate the execution.
#==============================================================================
_posix_adapter__touch__report_invalid_parameter() {
  reason="$1"
  details="$2"
  >&2 echo "ERROR | posix_adapter__touch | reason  | ${reason}"
  >&2 echo "ERROR | posix_adapter__touch | details | ${details}"
  _posix_adapter__touch__print_help
  exit 98
}

#==============================================================================
# Incompatible call error reporting helper function.
#------------------------------------------------------------------------------
# Globals:
#   None
# Options:
#   None
# Arguments:
#   [1] reason - Reason of the error.
#   [2] details - More details about the error.
# STDIN:
#   None
#------------------------------------------------------------------------------
# Output variables:
#   None
# STDOUT:
#   None
# STDERR:
#   Reported error.
# Status:
#   99  - The function will terminate the execution.
#==============================================================================
_posix_adapter__touch__report_incompatible_call() {
  reason="$1"
  details="$2"
  >&2 echo "ERROR | posix_adapter__touch | reason  | ${reason}"
  >&2 echo "ERROR | posix_adapter__touch | details | ${details}"
  _posix_adapter__touch__print_help
  exit 99
}

#==============================================================================
# ENTRY POINT
#==============================================================================

# If the script is called directly, call the internal function.
case $0 in
  *posix_adapter__touch)
    posix_adapter__touch "$@"
    ;;
esac
