#!/bin/sh
#==============================================================================
#             _     __ _  __
#   _ __ ___ | | __/ _(_)/ _| ___
#  | '_ ` _ \| |/ / |_| | |_ / _ \
#  | | | | | |   <|  _| |  _| (_) |
#  |_| |_| |_|_|\_\_| |_|_|  \___/
#==============================================================================
# TOOL: MKFIFO
#==============================================================================

_posix_adapter__mkfifo__print_help() {
  >&2 echo '=============================================================================='
  >&2 echo ''
  >&2 echo '  posix_adapter__mkfifo --help'
  >&2 echo '  posix_adapter__mkfifo <path>'
  >&2 echo ''
  >&2 echo '------------------------------------------------------------------------------'
  >&2 echo ' Execution mapping function for the "mkfifo" command line tool with a'
  >&2 echo ' uniform interface.'
  >&2 echo '------------------------------------------------------------------------------'
  >&2 echo ' Globals:'
  >&2 echo '   None'
  >&2 echo ' Options:'
  >&2 echo '   --help - Prints out the help message and exits.'
  >&2 echo ' Arguments:'
  >&2 echo '   [1] path - Path for the fifo.'
  >&2 echo ' STDIN:'
  >&2 echo '   Input passed to the mapped command.'
  >&2 echo '------------------------------------------------------------------------------'
  >&2 echo ' Output variables:'
  >&2 echo '   None'
  >&2 echo ' STDOUT:'
  >&2 echo '   Output of the mapped command.'
  >&2 echo ' STDERR:'
  >&2 echo '   Error output of the mapped command.'
  >&2 echo ' Status:'
  >&2 echo '   0  - Call was successful.'
  >&2 echo '   .. - Call failed with its error status.'
  >&2 echo '   98 - Invalid parameter configuration.'
  >&2 echo '   99 - No compatible call style was found.'
  >&2 echo '=============================================================================='
}

posix_adapter__mkfifo() {
  if [ "$#" -eq 0 ]
  then
    _posix_adapter__mkfifo__report_invalid_parameter \
      'Missing parameter!' \
      'A singular <path> parameter was expected!'
  elif [ "$#" -ne 1 ]
  then
    _posix_adapter__mkfifo__report_invalid_parameter \
      'Unexpected parameter count!' \
      "Only 1 parameter is expected, got ${#}!"
  fi

  case "$1" in
    --[!-]*)
      _posix_adapter__mkfifo__report_invalid_parameter \
        "Unexpected option '${1}'!" \
        'This function does not take options.'
      ;;
    -[!-]*)
      _posix_adapter__mkfifo__report_invalid_parameter \
        "Invalid single dashed option '${1}'!" \
        "posix_adapter only uses double dashed options like '--option'."
      ;;
  esac

  mkfifo "$1"
}

#==============================================================================
# Invalid parameter error reporting helper function.
#------------------------------------------------------------------------------
# Globals:
#   None
# Options:
#   None
# Arguments:
#   [1] reason - Reason of the error.
#   [2] details - More details about the error.
# STDIN:
#   None
#------------------------------------------------------------------------------
# Output variables:
#   None
# STDOUT:
#   None
# STDERR:
#   Reported error.
# Status:
#   98  - The function will terminate the execution.
#==============================================================================
_posix_adapter__mkfifo__report_invalid_parameter() {
  reason="$1"
  details="$2"
  >&2 echo "ERROR | posix_adapter__mkfifo | reason  | ${reason}"
  >&2 echo "ERROR | posix_adapter__mkfifo | details | ${details}"
  _posix_adapter__mkfifo__print_help
  exit 98
}

#==============================================================================
# Incompatible call error reporting helper function.
#------------------------------------------------------------------------------
# Globals:
#   None
# Options:
#   None
# Arguments:
#   [1] reason - Reason of the error.
#   [2] details - More details about the error.
# STDIN:
#   None
#------------------------------------------------------------------------------
# Output variables:
#   None
# STDOUT:
#   None
# STDERR:
#   Reported error.
# Status:
#   99  - The function will terminate the execution.
#==============================================================================
_posix_adapter__mkfifo__report_incompatible_call() {
  reason="$1"
  details="$2"
  >&2 echo "ERROR | posix_adapter__mkfifo | reason  | ${reason}"
  >&2 echo "ERROR | posix_adapter__mkfifo | details | ${details}"
  _posix_adapter__mkfifo__print_help
  exit 99
}

#==============================================================================
# ENTRY POINT
#==============================================================================

# If the script is called directly, call the internal function.
case $0 in
  *posix_adapter__mkfifo)
    posix_adapter__mkfifo "$@"
    ;;
esac
