#!/bin/sh
#==============================================================================
#    __ _           _
#   / _(_)_ __   __| |
#  | |_| | '_ \ / _` |
#  |  _| | | | | (_| |
#  |_| |_|_| |_|\__,_|
#==============================================================================
# TOOL: FIND
#==============================================================================

_posix_adapter__find__print_help() {
  >&2 echo '=============================================================================='
  >&2 echo ''
  >&2 echo '  posix_adapter__find --help'
  >&2 echo '  posix_adapter__find <path> [--type <type>] [--name <name>] [--name <name>]'
  >&2 echo '    [--min-depth <min-depth>] [--max-depth <max-depth>] [--print0]'
  >&2 echo ''
  >&2 echo '------------------------------------------------------------------------------'
  >&2 echo ' Execution mapping function for the "find" command line tool with a uniform'
  >&2 echo ' interface.'
  >&2 echo '------------------------------------------------------------------------------'
  >&2 echo ' Globals:'
  >&2 echo '   None'
  >&2 echo ' Options:'
  >&2 echo '   --help - Prints out the help message and exits.'
  >&2 echo '   --type <type> - find compatible type specifier string.'
  >&2 echo '   --name <name> - find compatible name specifier string.'
  >&2 echo '   --min-depth <depth> - find compatible search min depth specifier.'
  >&2 echo '   --max-depth <depth> - find compatible search max depth specifier.'
  >&2 echo '   --same-file <path> - find compatible same file parameter.'
  >&2 echo '   --print0 - print null separated results.'
  >&2 echo ' Arguments:'
  >&2 echo '   [1] path - Path where the search should be executed.'
  >&2 echo ' STDIN:'
  >&2 echo '   Input passed to the mapped command.'
  >&2 echo '------------------------------------------------------------------------------'
  >&2 echo ' Output variables:'
  >&2 echo '   None'
  >&2 echo ' STDOUT:'
  >&2 echo '   Output of the mapped command.'
  >&2 echo ' STDERR:'
  >&2 echo '   Error output of the mapped command.'
  >&2 echo ' Status:'
  >&2 echo '   0  - Call was successful.'
  >&2 echo '   .. - Call failed with its error status.'
  >&2 echo '   98 - Invalid parameter configuration.'
  >&2 echo '   99 - No compatible call style was found.'
  >&2 echo '=============================================================================='
}

posix_adapter__find() {
  posix_adapter__flag__type='0'
  posix_adapter__value__type=''

  posix_adapter__flag__name='0'
  posix_adapter__value__name=''

  posix_adapter__flag__min_depth='0'
  posix_adapter__value__min_depth=''

  posix_adapter__flag__max_depth='0'
  posix_adapter__value__max_depth=''

  posix_adapter__flag__same_file='0'
  posix_adapter__value__same_file=''

  posix_adapter__flag__print0='0'

  # This flag is only used to determine if the path was already set.
  posix_adapter__flag__path='0'
  # This is a unusual processing of this positional parameter. As not all find
  # implementation has a default path, this value is always present and it is
  # only updated if needed. It is also independent of the decision string.
  posix_adapter__value__path='.'

  while [ "$#" -gt '0' ]
  do
    case "$1" in
      --type)
        posix_adapter__flag__type='1'
        posix_adapter__value__type="$2"
        shift
        shift
        ;;
      --name)
        posix_adapter__flag__name='1'
        posix_adapter__value__name="$2"
        shift
        shift
        ;;
      --min-depth)
        posix_adapter__flag__min_depth='1'
        posix_adapter__value__min_depth="$2"
        shift
        shift
        ;;
      --max-depth)
        posix_adapter__flag__max_depth='1'
        posix_adapter__value__max_depth="$2"
        shift
        shift
        ;;
      --same-file)
        posix_adapter__flag__same_file='1'
        posix_adapter__value__same_file="$2"
        shift
        shift
        ;;
      --print0)
        posix_adapter__flag__print0='1'
        shift
        ;;
      --[!-]*)
        _posix_adapter__find__report_invalid_parameter \
          "Unexpected option '${1}'!" \
          'You can only use the available options.'
        ;;
      -[!-]*)
        _posix_adapter__find__report_invalid_parameter \
          "Invalid single dashed option '${1}'!" \
          "posix_adapter only uses double dashed options like '--option'."
        ;;
      *)
        # Only one file is needed for now.
        if [ "$posix_adapter__flag__path" -eq '0' ]
        then
          posix_adapter__flag__path='1'
          posix_adapter__value__path="$1"
          shift
        else
          _posix_adapter__find__report_invalid_parameter \
            'Unexpected parameter!' \
            "Parameter '${1}' is unexpected!"
        fi
        ;;
    esac
  done

  # Assembling the decision string. Max depth sohuld be the first as find
  # processes its parameters sequentially. MAx-depth - type - name should be
  # the priority order.
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
  # 000000
  posix_adapter__decision="${posix_adapter__flag__min_depth}"
  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__max_depth}"
  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__type}"
  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__name}"
  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__same_file}"
  posix_adapter__decision="${posix_adapter__decision}${posix_adapter__flag__print0}"

  _posix_adapter__find__common \
    "$posix_adapter__decision" \
    "$posix_adapter__value__type" \
    "$posix_adapter__value__name" \
    "$posix_adapter__value__min_depth" \
    "$posix_adapter__value__max_depth" \
    "$posix_adapter__value__same_file" \
    "$posix_adapter__value__path"
}

#==============================================================================
# Common call mapping function.
#------------------------------------------------------------------------------
# Globals:
#   None
# Options:
#   None
# Arguments:
#   [1] decision_string - String that decodes the optional parameter presence.
#   [2] value_type -  Value passed with the type flag.
#   [3] value_name - Value passed with the name flag.
#   [4] value_min_depth - Value passed with the max_depth flag.
#   [5] value_max_depth - Value passed with the max_depth flag.
#   [6] value_same_file - Value passed with the same_file flag.
#   [7] value_path - Path that should be the base of the search.
# STDIN:
#   Input passed to the mapped command.
#------------------------------------------------------------------------------
# Output variables:
#   None
# STDOUT:
#   Mapped command's output.
# STDERR:
#   Mapped command's error output. Mapping error output.
# Status:
#   0  - Call succeeded.
#   .. - Call failed with it's error status
#==============================================================================
_posix_adapter__find__common() {
  posix_adapter__decision_string="$1"
  posix_adapter__value__type="$2"
  posix_adapter__value__name="$3"
  posix_adapter__value__min_depth="$4"
  posix_adapter__value__max_depth="$5"
  posix_adapter__value__same_file="$6"
  posix_adapter__value__path="$7"

  case "$posix_adapter__decision_string" in
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    000000)
      find \
        "$posix_adapter__value__path" \
        \
        \
        \
        \
        \
        \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    000001)
      find \
        "$posix_adapter__value__path" \
        \
        \
        \
        \
        \
        -print0 \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    000010)
      find \
        "$posix_adapter__value__path" \
        \
        \
        \
        \
        -samefile "$posix_adapter__value__same_file" \
        \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    000011)
      find \
        "$posix_adapter__value__path" \
        \
        \
        \
        \
        -samefile "$posix_adapter__value__same_file" \
        -print0 \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    000100)
      find \
        "$posix_adapter__value__path" \
        \
        \
        \
        -name "$posix_adapter__value__name" \
        \
        \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    000101)
      find \
        "$posix_adapter__value__path" \
        \
        \
        \
        -name "$posix_adapter__value__name" \
        \
        -print0 \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    000110)
      find \
        "$posix_adapter__value__path" \
        \
        \
        \
        -name "$posix_adapter__value__name" \
        -samefile "$posix_adapter__value__same_file" \
        \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    000111)
      find \
        "$posix_adapter__value__path" \
        \
        \
        \
        -name "$posix_adapter__value__name" \
        -samefile "$posix_adapter__value__same_file" \
        -print0 \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    001000)
      find \
        "$posix_adapter__value__path" \
        \
        \
        -type "$posix_adapter__value__type" \
        \
        \
        \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    001001)
      find \
        "$posix_adapter__value__path" \
        \
        \
        -type "$posix_adapter__value__type" \
        \
        \
        -print0 \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    001010)
      find \
        "$posix_adapter__value__path" \
        \
        \
        -type "$posix_adapter__value__type" \
        \
        -samefile "$posix_adapter__value__same_file" \
        \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    001011)
      find \
        "$posix_adapter__value__path" \
        \
        \
        -type "$posix_adapter__value__type" \
        \
        -samefile "$posix_adapter__value__same_file" \
        -print0 \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    001100)
      find \
        "$posix_adapter__value__path" \
        \
        \
        -type "$posix_adapter__value__type" \
        -name "$posix_adapter__value__name" \
        \
        \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    001101)
      find \
        "$posix_adapter__value__path" \
        \
        \
        -type "$posix_adapter__value__type" \
        -name "$posix_adapter__value__name" \
        \
        -print0 \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    001110)
      find \
        "$posix_adapter__value__path" \
        \
        \
        -type "$posix_adapter__value__type" \
        -name "$posix_adapter__value__name" \
        -samefile "$posix_adapter__value__same_file" \
        \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    001111)
      find \
        "$posix_adapter__value__path" \
        \
        \
        -type "$posix_adapter__value__type" \
        -name "$posix_adapter__value__name" \
        -samefile "$posix_adapter__value__same_file" \
        -print0 \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    010000)
      find \
        "$posix_adapter__value__path" \
        \
        -maxdepth "$posix_adapter__value__max_depth" \
        \
        \
        \
        \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    010001)
      find \
        "$posix_adapter__value__path" \
        \
        -maxdepth "$posix_adapter__value__max_depth" \
        \
        \
        \
        -print0 \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    010010)
      find \
        "$posix_adapter__value__path" \
        \
        -maxdepth "$posix_adapter__value__max_depth" \
        \
        \
        -samefile "$posix_adapter__value__same_file" \
        \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    010011)
      find \
        "$posix_adapter__value__path" \
        \
        -maxdepth "$posix_adapter__value__max_depth" \
        \
        \
        -samefile "$posix_adapter__value__same_file" \
        -print0 \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    010100)
      find \
        "$posix_adapter__value__path" \
        \
        -maxdepth "$posix_adapter__value__max_depth" \
        \
        -name "$posix_adapter__value__name" \
        \
        \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    010101)
      find \
        "$posix_adapter__value__path" \
        \
        -maxdepth "$posix_adapter__value__max_depth" \
        \
        -name "$posix_adapter__value__name" \
        \
        -print0 \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    010110)
      find \
        "$posix_adapter__value__path" \
        \
        -maxdepth "$posix_adapter__value__max_depth" \
        \
        -name "$posix_adapter__value__name" \
        -samefile "$posix_adapter__value__same_file" \
        \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    010111)
      find \
        "$posix_adapter__value__path" \
        \
        -maxdepth "$posix_adapter__value__max_depth" \
        \
        -name "$posix_adapter__value__name" \
        -samefile "$posix_adapter__value__same_file" \
        -print0 \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    011000)
      find \
        "$posix_adapter__value__path" \
        \
        -maxdepth "$posix_adapter__value__max_depth" \
        -type "$posix_adapter__value__type" \
        \
        \
        \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    011001)
      find \
        "$posix_adapter__value__path" \
        \
        -maxdepth "$posix_adapter__value__max_depth" \
        -type "$posix_adapter__value__type" \
        \
        \
        -print0 \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    011010)
      find \
        "$posix_adapter__value__path" \
        \
        -maxdepth "$posix_adapter__value__max_depth" \
        -type "$posix_adapter__value__type" \
        \
        -samefile "$posix_adapter__value__same_file" \
        \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    011011)
      find \
        "$posix_adapter__value__path" \
        \
        -maxdepth "$posix_adapter__value__max_depth" \
        -type "$posix_adapter__value__type" \
        \
        -samefile "$posix_adapter__value__same_file" \
        -print0 \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    011100)
      find \
        "$posix_adapter__value__path" \
        \
        -maxdepth "$posix_adapter__value__max_depth" \
        -type "$posix_adapter__value__type" \
        -name "$posix_adapter__value__name" \
        \
        \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    011101)
      find \
        "$posix_adapter__value__path" \
        \
        -maxdepth "$posix_adapter__value__max_depth" \
        -type "$posix_adapter__value__type" \
        -name "$posix_adapter__value__name" \
        \
        -print0 \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    011110)
      find \
        "$posix_adapter__value__path" \
        \
        -maxdepth "$posix_adapter__value__max_depth" \
        -type "$posix_adapter__value__type" \
        -name "$posix_adapter__value__name" \
        -samefile "$posix_adapter__value__same_file" \
        \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    011111)
      find \
        "$posix_adapter__value__path" \
        \
        -maxdepth "$posix_adapter__value__max_depth" \
        -type "$posix_adapter__value__type" \
        -name "$posix_adapter__value__name" \
        -samefile "$posix_adapter__value__same_file" \
        -print0 \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    100000)
      find \
        "$posix_adapter__value__path" \
        -mindepth "$posix_adapter__value__min_depth" \
        \
        \
        \
        \
        \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    100001)
      find \
        "$posix_adapter__value__path" \
        -mindepth "$posix_adapter__value__min_depth" \
        \
        \
        \
        \
        -print0 \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    100010)
      find \
        "$posix_adapter__value__path" \
        -mindepth "$posix_adapter__value__min_depth" \
        \
        \
        \
        -samefile "$posix_adapter__value__same_file" \
        \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    100011)
      find \
        "$posix_adapter__value__path" \
        -mindepth "$posix_adapter__value__min_depth" \
        \
        \
        \
        -samefile "$posix_adapter__value__same_file" \
        -print0 \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    100100)
      find \
        "$posix_adapter__value__path" \
        -mindepth "$posix_adapter__value__min_depth" \
        \
        \
        -name "$posix_adapter__value__name" \
        \
        \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    100101)
      find \
        "$posix_adapter__value__path" \
        -mindepth "$posix_adapter__value__min_depth" \
        \
        \
        -name "$posix_adapter__value__name" \
        \
        -print0 \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    100110)
      find \
        "$posix_adapter__value__path" \
        -mindepth "$posix_adapter__value__min_depth" \
        \
        \
        -name "$posix_adapter__value__name" \
        -samefile "$posix_adapter__value__same_file" \
        \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    100111)
      find \
        "$posix_adapter__value__path" \
        -mindepth "$posix_adapter__value__min_depth" \
        \
        \
        -name "$posix_adapter__value__name" \
        -samefile "$posix_adapter__value__same_file" \
        -print0 \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    101000)
      find \
        "$posix_adapter__value__path" \
        -mindepth "$posix_adapter__value__min_depth" \
        \
        -type "$posix_adapter__value__type" \
        \
        \
        \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    101001)
      find \
        "$posix_adapter__value__path" \
        -mindepth "$posix_adapter__value__min_depth" \
        \
        -type "$posix_adapter__value__type" \
        \
        \
        -print0 \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    101010)
      find \
        "$posix_adapter__value__path" \
        -mindepth "$posix_adapter__value__min_depth" \
        \
        -type "$posix_adapter__value__type" \
        \
        -samefile "$posix_adapter__value__same_file" \
        \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    101011)
      find \
        "$posix_adapter__value__path" \
        -mindepth "$posix_adapter__value__min_depth" \
        \
        -type "$posix_adapter__value__type" \
        \
        -samefile "$posix_adapter__value__same_file" \
        -print0 \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    101100)
      find \
        "$posix_adapter__value__path" \
        -mindepth "$posix_adapter__value__min_depth" \
        \
        -type "$posix_adapter__value__type" \
        -name "$posix_adapter__value__name" \
        \
        \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    101101)
      find \
        "$posix_adapter__value__path" \
        -mindepth "$posix_adapter__value__min_depth" \
        \
        -type "$posix_adapter__value__type" \
        -name "$posix_adapter__value__name" \
        \
        -print0 \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    101110)
      find \
        "$posix_adapter__value__path" \
        -mindepth "$posix_adapter__value__min_depth" \
        \
        -type "$posix_adapter__value__type" \
        -name "$posix_adapter__value__name" \
        -samefile "$posix_adapter__value__same_file" \
        \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    101111)
      find \
        "$posix_adapter__value__path" \
        -mindepth "$posix_adapter__value__min_depth" \
        \
        -type "$posix_adapter__value__type" \
        -name "$posix_adapter__value__name" \
        -samefile "$posix_adapter__value__same_file" \
        -print0 \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    110000)
      find \
        "$posix_adapter__value__path" \
        -mindepth "$posix_adapter__value__min_depth" \
        -maxdepth "$posix_adapter__value__max_depth" \
        \
        \
        \
        \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    110001)
      find \
        "$posix_adapter__value__path" \
        -mindepth "$posix_adapter__value__min_depth" \
        -maxdepth "$posix_adapter__value__max_depth" \
        \
        \
        \
        -print0 \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    110010)
      find \
        "$posix_adapter__value__path" \
        -mindepth "$posix_adapter__value__min_depth" \
        -maxdepth "$posix_adapter__value__max_depth" \
        \
        \
        -samefile "$posix_adapter__value__same_file" \
        \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    110011)
      find \
        "$posix_adapter__value__path" \
        -mindepth "$posix_adapter__value__min_depth" \
        -maxdepth "$posix_adapter__value__max_depth" \
        \
        \
        -samefile "$posix_adapter__value__same_file" \
        -print0 \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    110100)
      find \
        "$posix_adapter__value__path" \
        -mindepth "$posix_adapter__value__min_depth" \
        -maxdepth "$posix_adapter__value__max_depth" \
        \
        -name "$posix_adapter__value__name" \
        \
        \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    110101)
      find \
        "$posix_adapter__value__path" \
        -mindepth "$posix_adapter__value__min_depth" \
        -maxdepth "$posix_adapter__value__max_depth" \
        \
        -name "$posix_adapter__value__name" \
        \
        -print0 \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    110110)
      find \
        "$posix_adapter__value__path" \
        -mindepth "$posix_adapter__value__min_depth" \
        -maxdepth "$posix_adapter__value__max_depth" \
        \
        -name "$posix_adapter__value__name" \
        -samefile "$posix_adapter__value__same_file" \
        \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    110111)
      find \
        "$posix_adapter__value__path" \
        -mindepth "$posix_adapter__value__min_depth" \
        -maxdepth "$posix_adapter__value__max_depth" \
        \
        -name "$posix_adapter__value__name" \
        -samefile "$posix_adapter__value__same_file" \
        -print0 \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    111000)
      find \
        "$posix_adapter__value__path" \
        -mindepth "$posix_adapter__value__min_depth" \
        -maxdepth "$posix_adapter__value__max_depth" \
        -type "$posix_adapter__value__type" \
        \
        \
        \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    111001)
      find \
        "$posix_adapter__value__path" \
        -mindepth "$posix_adapter__value__min_depth" \
        -maxdepth "$posix_adapter__value__max_depth" \
        -type "$posix_adapter__value__type" \
        \
        \
        -print0 \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    111010)
      find \
        "$posix_adapter__value__path" \
        -mindepth "$posix_adapter__value__min_depth" \
        -maxdepth "$posix_adapter__value__max_depth" \
        -type "$posix_adapter__value__type" \
        \
        -samefile "$posix_adapter__value__same_file" \
        \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    111011)
      find \
        "$posix_adapter__value__path" \
        -mindepth "$posix_adapter__value__min_depth" \
        -maxdepth "$posix_adapter__value__max_depth" \
        -type "$posix_adapter__value__type" \
        \
        -samefile "$posix_adapter__value__same_file" \
        -print0 \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    111100)
      find \
        "$posix_adapter__value__path" \
        -mindepth "$posix_adapter__value__min_depth" \
        -maxdepth "$posix_adapter__value__max_depth" \
        -type "$posix_adapter__value__type" \
        -name "$posix_adapter__value__name" \
        \
        \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    111101)
      find \
        "$posix_adapter__value__path" \
        -mindepth "$posix_adapter__value__min_depth" \
        -maxdepth "$posix_adapter__value__max_depth" \
        -type "$posix_adapter__value__type" \
        -name "$posix_adapter__value__name" \
        \
        -print0 \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    111110)
      find \
        "$posix_adapter__value__path" \
        -mindepth "$posix_adapter__value__min_depth" \
        -maxdepth "$posix_adapter__value__max_depth" \
        -type "$posix_adapter__value__type" \
        -name "$posix_adapter__value__name" \
        -samefile "$posix_adapter__value__same_file" \
        \

      ;;
  # ,------- min_depth
  # |,------ max_depth
  # ||,----- type
  # |||,---- name
  # ||||,--- same_file
  # |||||,-- print0
    111111)
      find \
        "$posix_adapter__value__path" \
        -mindepth "$posix_adapter__value__min_depth" \
        -maxdepth "$posix_adapter__value__max_depth" \
        -type "$posix_adapter__value__type" \
        -name "$posix_adapter__value__name" \
        -samefile "$posix_adapter__value__same_file" \
        -print0 \

      ;;
    *)
      _posix_adapter__find__report_incompatible_call \
        'Unexpected parameter combination!' \
        'You can only use the available options.'
      ;;
  esac
}

#==============================================================================
# Invalid parameter error reporting helper function.
#------------------------------------------------------------------------------
# Globals:
#   None
# Options:
#   None
# Arguments:
#   [1] reason - Reason of the error.
#   [2] details - More details about the error.
# STDIN:
#   None
#------------------------------------------------------------------------------
# Output variables:
#   None
# STDOUT:
#   None
# STDERR:
#   Reported error.
# Status:
#   98  - The function will terminate the execution.
#==============================================================================
_posix_adapter__find__report_invalid_parameter() {
  reason="$1"
  details="$2"
  >&2 echo "ERROR | posix_adapter__find | reason  | ${reason}"
  >&2 echo "ERROR | posix_adapter__find | details | ${details}"
  _posix_adapter__find__print_help
  exit 98
}

#==============================================================================
# Incompatible call error reporting helper function.
#------------------------------------------------------------------------------
# Globals:
#   None
# Options:
#   None
# Arguments:
#   [1] reason - Reason of the error.
#   [2] details - More details about the error.
# STDIN:
#   None
#------------------------------------------------------------------------------
# Output variables:
#   None
# STDOUT:
#   None
# STDERR:
#   Reported error.
# Status:
#   99  - The function will terminate the execution.
#==============================================================================
_posix_adapter__find__report_incompatible_call() {
  reason="$1"
  details="$2"
  >&2 echo "ERROR | posix_adapter__find | reason  | ${reason}"
  >&2 echo "ERROR | posix_adapter__find | details | ${details}"
  _posix_adapter__find__print_help
  exit 99
}

#==============================================================================
# ENTRY POINT
#==============================================================================

# If the script is called directly, call the internal function.
case $0 in
  *posix_adapter__find)
    posix_adapter__find "$@"
    ;;
esac
